name: "Build and Test"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  local-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: github-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: true
    - run: >
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: >
        export NIXPKGS_ALLOW_UNFREE=1 && nix-shell --run "cpp-helper make all"
    - run: >
        [[ -f build/unit-tests ]] || false
  thorough-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: github-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: true
    - run: >
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: >
        export NIXPKGS_ALLOW_UNFREE=1 && nix-shell --run "cpp-helper challenge all"
    - run: >
        [[ -f build/unit-tests ]] || false
